# Generated by Django 2.1 on 2021-02-10 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='dete',
            new_name='date',
        ),
    ]
